import React from "react";
export const AirPressure = React.lazy(() => import("../../Screens/Consumption/AirPressure/AirPressure"));
export const BatchInformation = React.lazy(() => import("../../Screens/Production/BatchInformation/BatchInformation"));
export const ColorChange = React.lazy(() => import("../../Screens/Production/ColorChange/ColorChange"));
export const ElectricityAir = React.lazy(() => import("../../Screens/Consumption/ElectricityAir/ElectricityAir"));
export const FreshPowder = React.lazy(() => import("../../Screens/Consumption/FreshPowder/FreshPowder"));
export const HumidityTemperature = React.lazy(() => import("../../Screens/Consumption/HumidityTemperature/HumidityTemperature"));
export const Monitoring = React.lazy(() => import("../../Screens/Production/Monitoring/Monitoring"));
export const PowderType = React.lazy(() => import("../../Screens/Consumption/PowderType/PowderType"));
export const SprayedPowder = React.lazy(() => import("../../Screens/Consumption/SprayedPowder/SprayedPowder"));